import type { Metadata } from "next";
import { Header } from "@/components/header/header"
import { Footer } from "@/components/Footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("отрисовка Favlayout")
  return (
    <>
      <Header/>
        {children}
      <Footer/>
    </>
   
  );
}
 